#!/bin/sh

sleep 0.3
status=$(playerctl status)

if [ "$status" = Playing ]; then
	if [[ $(playerctl metadata | grep artUrl) == "" ]];
	then
		albumart=$(playerctl metadata xesam:url | cut -f3 -d":" | sed 's/%20/ /g')
		albumartfetch=$(ffmpeg -hide_banner -loglevel panic -i "/home/barbarossa/Music/$albumart" /tmp/cover.png -y)
		info=$(playerctl metadata --format $' Now Playing\n {{ title }} ({{ duration(mpris:length) }})\n {{ artist }}\n {{ album }}')
		notify-send -t 5000 -u normal -i /tmp/cover.png "$info"		
		#dunstify -t 5000 -r 7658 -u normal -i /tmp/cover.png "$info"
	else
		albumartspot=$(playerctl metadata mpris:artUrl)
		albumartfetchspot=$(curl -s --output /tmp/cover.png $albumartspot)
		info=$(playerctl metadata --format $' Now Playing\n {{ title }} ({{ duration(mpris:length) }})\n {{ artist }}\n {{ album }}')
		notify-send -t 5000 -u normal -i /tmp/cover.png "$info"		
		#dunstify -t 5000 -r 7658 -u normal -i /tmp/cover.png "$info"
	fi
elif [ "$status" = Paused ]; then
	position=$(playerctl position --format "{{ duration(position) }}")
	duration=$(playerctl metadata --format "{{ duration(mpris:length) }}")
	formatted=$' Playback Paused\nCurrent Position: '$position'/'$duration''
	notify-send -t 3000 -u normal "$formatted"	
	#dunstify -t 3000 -r 7658 -u normal "$formatted"
elif [ "$status" = Stopped ]; then
	position=$(playerctl position --format "{{ duration(position) }}")
	duration=$(playerctl metadata --format "{{ duration(mpris:length) }}")
	formatted=$' Playback Stopped\nCurrent Position: '$position'/'$duration''
	notify-send -t 3000 -u normal "$formatted"	
	#dunstify -t 3000 -r 7658 -u normal "$formatted"
else
	notify-send -t 3000 -u normal $'Something else besides play/paused happened.\nUpdate this script fool.'	
	#dunstify -t 3000 -r 7658 -u normal $'Something else besides play/paused happened.\nUpdate this script fool.'
fi

